Fix design
calypsonet/keyple-android-demo-validation pull request #11
Opened 2020-11-20 02:27 UTC by cedrtang

2020-11-20 09:43 UTC, Yamapps requested changes

2020-11-20 09:43 UTC, Yamapps commented on validator-app/src/main/kotlin/org/eclipse/keyple/famoco/validator/ui/activities/SplashScreenActivity.kt
> +            override fun run() {
No need for a timer here, Wizway will not be integrated into this app

2020-11-23 14:41 UTC, ocfmem approved these changes

2020-11-23 14:57 UTC, Yamapps approved these changes

2020-11-23 14:58 UTC, merged